/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsGalleryRouteImport } from './routes/projects-gallery'
import { Route as NewsBlogsRouteImport } from './routes/news-blogs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectDetailsProjectIdRouteImport } from './routes/project-details/$projectId'
import { Route as NewWorkDetailsNewsBlogsIdRouteImport } from './routes/new-work-details/$newsBlogsId'

const ProjectsGalleryRoute = ProjectsGalleryRouteImport.update({
  id: '/projects-gallery',
  path: '/projects-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsBlogsRoute = NewsBlogsRouteImport.update({
  id: '/news-blogs',
  path: '/news-blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectDetailsProjectIdRoute = ProjectDetailsProjectIdRouteImport.update({
  id: '/project-details/$projectId',
  path: '/project-details/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const NewWorkDetailsNewsBlogsIdRoute =
  NewWorkDetailsNewsBlogsIdRouteImport.update({
    id: '/new-work-details/$newsBlogsId',
    path: '/new-work-details/$newsBlogsId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/news-blogs': typeof NewsBlogsRoute
  '/projects-gallery': typeof ProjectsGalleryRoute
  '/new-work-details/$newsBlogsId': typeof NewWorkDetailsNewsBlogsIdRoute
  '/project-details/$projectId': typeof ProjectDetailsProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/news-blogs': typeof NewsBlogsRoute
  '/projects-gallery': typeof ProjectsGalleryRoute
  '/new-work-details/$newsBlogsId': typeof NewWorkDetailsNewsBlogsIdRoute
  '/project-details/$projectId': typeof ProjectDetailsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/news-blogs': typeof NewsBlogsRoute
  '/projects-gallery': typeof ProjectsGalleryRoute
  '/new-work-details/$newsBlogsId': typeof NewWorkDetailsNewsBlogsIdRoute
  '/project-details/$projectId': typeof ProjectDetailsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/news-blogs'
    | '/projects-gallery'
    | '/new-work-details/$newsBlogsId'
    | '/project-details/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/news-blogs'
    | '/projects-gallery'
    | '/new-work-details/$newsBlogsId'
    | '/project-details/$projectId'
  id:
    | '__root__'
    | '/'
    | '/news-blogs'
    | '/projects-gallery'
    | '/new-work-details/$newsBlogsId'
    | '/project-details/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewsBlogsRoute: typeof NewsBlogsRoute
  ProjectsGalleryRoute: typeof ProjectsGalleryRoute
  NewWorkDetailsNewsBlogsIdRoute: typeof NewWorkDetailsNewsBlogsIdRoute
  ProjectDetailsProjectIdRoute: typeof ProjectDetailsProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects-gallery': {
      id: '/projects-gallery'
      path: '/projects-gallery'
      fullPath: '/projects-gallery'
      preLoaderRoute: typeof ProjectsGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news-blogs': {
      id: '/news-blogs'
      path: '/news-blogs'
      fullPath: '/news-blogs'
      preLoaderRoute: typeof NewsBlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-details/$projectId': {
      id: '/project-details/$projectId'
      path: '/project-details/$projectId'
      fullPath: '/project-details/$projectId'
      preLoaderRoute: typeof ProjectDetailsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-work-details/$newsBlogsId': {
      id: '/new-work-details/$newsBlogsId'
      path: '/new-work-details/$newsBlogsId'
      fullPath: '/new-work-details/$newsBlogsId'
      preLoaderRoute: typeof NewWorkDetailsNewsBlogsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewsBlogsRoute: NewsBlogsRoute,
  ProjectsGalleryRoute: ProjectsGalleryRoute,
  NewWorkDetailsNewsBlogsIdRoute: NewWorkDetailsNewsBlogsIdRoute,
  ProjectDetailsProjectIdRoute: ProjectDetailsProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
